
Vagrant.configure("2") do |config|
    config.vm.box = "almalinux/9"

    config.vm.define "controlplane", primary: true do |cp|
        cp.vm.hostname = "controlplane"
        cp.vm.network "private_network", ip: "172.23.0.254"
        cp.vm.provider "virtualbox" do |vb|
            vb.memory = 4096
            vb.cpus = 2
            vb.name = "k8s-controlplane"
        end
    end

#     (1..1).each do |i|
#         config.vm.define "worker#{i}" do |worker|
#             worker.vm.hostname = "worker#{i}"
#             worker.vm.network "private_network", ip: "172.23.0.#{1 + i}"
#             worker.vm.provider "virtualbox" do |vb|
#                 vb.memory = 1024
#                 vb.cpus = 1
#                 vb.name = "k8s-worker#{i}"
#             end
#         end
#     end

    config.vm.provision "shell", path: "kubernetes.sh"
end